### ISSUE TITLE
Cloud publish iOS fails with  'An error has occurred while uploading the package' Error: "[object Object]"

### ISSUE THREAD

**Issue by ok200paul** [ProgressNS/sidekick-feedback#459]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Cloud publish iOS fails with `[object Object]` error. It appears to be at the upload-to-apple stage. The publish process appears to go through the build step and the download step. It then asks me for the .p12 password, and appears to authenticate me OK to the apple developer platform when it prompts for login. It then notifies:

```
[20-01-20 17:06:42.957] (CLI) Starting publishing.
[20-01-20 17:06:46.901] (CLI) Build machine host name: administrators-Mac-19.local
```
.. but fails around 16 minutes later with:
```
[20-01-20 17:21:50.972] [object Object]
, Error: [object Object]
    at CloudPublishService.getiOSError (/Users/MYUSERNAME/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-publish-service.js:79:21)
    at CloudPublishService.<anonymous> (/Users/MYUSERNAME/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-publish-service.js:96:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/MYUSERNAME/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-publish-service.js:4:58)
```

![image](https://user-images.githubusercontent.com/22406523/72705016-6c90d200-3bae-11ea-8fbd-d2398b08f557.png)

### Which platform(s) does the issue occur on?
iOS
macOS

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:**  Version: 1.19.2-v.2019.11.18.2 (latest)
- **NativeScript CLI:**  6.3.3
- **CLI extension nativescript-cloud:**  1.19.3
- **CLI extension nativescript-starter-kits:** 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start nativescript sidekick, verify app works on emulators
2. Publish app, enter p12 password
3. Go through build stage and download stage
4. Begin publish stage
5. Get prompted for iOS developer credentials, enter in OK
6. Publishing begins - fails with error: [object Object]

### Does this issue happen every time?
Yes

### Send the client logs
https://gist.github.com/ok200paul/65f164868783910fd29ca489f5fdda8c

**Comment by ok200paul** [comment]
To add to this: uploading the IPA using the Apple "Transporter" app, works fine.

**Comment by ok200paul** [comment]
> To add to this: uploading the IPA using the Apple "Transporter" app, works fine.

After testing on a real device through testflight, the app crashes. So to recap, app appears to build, outputs IPA, fails to upload through NSS with unknown error. Let me know if I can provide anything further. Paul
